version: '3'

services:
  www:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html

  db:
    image: mysql:8
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password

  adminer:
    image: adminer
    ports:
      - 9090:8080
